# Generated by Django 3.2.3 on 2021-05-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='VCInvestor/static/london.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='stage',
            field=models.CharField(choices=[('series b', 'Series B'), ('series c', 'Series C'), ('series d', 'Series D'), ('series e', 'Series E')], max_length=100),
        ),
    ]
