# Generated by Django 3.2.3 on 2021-05-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0003_auto_20210530_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
    ]
