# Generated by Django 3.2.3 on 2021-05-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investor', '0004_alter_company_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('fintech', 'Fintech'), ('technology', 'Technology'), ('enterprise', 'Enterprise'), ('travel', 'Travel'), ('healthcare', 'Healthcare'), ('robotics', 'Robotics')], max_length=100),
        ),
    ]
